# =====================================================
# CREATING A DJANGO APP
# =====================================================

# Syntax:
'''python manage.py startapp student'''

# After creating the app, the project structure becomes:
#
# FirstProject/
# ├── manage.py
# ├── FirstProject/
# └── student/
#
# The app contains models, views, admin, tests, etc.

# Display all available commands
'''python manage.py help'''


'''student/
│
├── migrations/              # Stores database migration files
│   └── __init__.py
│
├── __init__.py              # Makes this folder a Python package
│
├── admin.py                 # Register models for Django Admin
│
├── apps.py                  # App configuration
│
├── models.py                # Database models (tables)
│
├── tests.py                 # Unit test cases
│
├── views.py                 # Business logic and request handling
│
└── urls.py                  # URL routing (Created manually)'''

# =====================================================
### admin.py
# Used to register models in Django Admin Panel.
# Registered models become manageable through the admin interface.

### apps.py
# Stores application configuration.

### models.py
# Used to create database tables using Python classes.

### views.py
# Contains business logic.
# Receives requests and returns responses.

### tests.py
# Used for writing automated test cases.

### migrations/
# Stores migration files generated by:
# python manage.py makemigrations
# These files keep track of database schema changes.

# =====================================================
### REGISTERING AN APP
# Open:
# FirstProject/settings.py
# Locate INSTALLED_APPS
# Register your application here

# =====================================================
'''
### settings.py

# This file contains all project configuration.

# Project Secret Key
SECRET_KEY = "your-secret-key"

# Debug Mode
DEBUG = True

# Allowed Hosts
ALLOWED_HOSTS = []

# Installed Applications
INSTALLED_APPS = [
    ...
]

# Middleware
MIDDLEWARE = [
    ...
]

# Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Language
LANGUAGE_CODE = 'en-us'

# Time Zone
TIME_ZONE = 'UTC'

# Static Files Folder
STATIC_URL = 'static/'

# Default Primary Key
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField' '''

# DEBUG
# True  -> Development
# False -> Production

# INSTALLED_APPS
# List of all installed Django applications.

# DATABASES
# Database connection details.

# STATIC_URL
# URL used for CSS, JavaScript, and Images.

# TIME_ZONE
# Sets the project's timezone.

# LANGUAGE_CODE
# Sets the default language.

# =====================================================
### START DJANGO SERVER

# Default Port
'''python manage.py runserver'''

# Custom Port
'''python manage.py runserver 8001'''

# Run Server on All Network Interfaces
'''python manage.py runserver 0.0.0.0:8000'''

# =====================================================
### COMMON DJANGO COMMANDS

# Create a new app
'''python manage.py startapp student'''

# Start development server
'''python manage.py runserver'''

# Create migration files
'''python manage.py makemigrations'''

# Apply migrations to database
'''python manage.py migrate'''

# Create admin user
'''python manage.py createsuperuser'''

# Open Django shell
'''python manage.py shell'''

# Collect static files (Production)
'''python manage.py collectstatic'''

# Check project for errors
'''python manage.py check'''

# Show SQL generated by migrations
'''python manage.py sqlmigrate app_name migration_number'''

# Show all registered URLs
'''python manage.py show_urls'''   # Requires django-extensions

# Display all available commands
'''python manage.py help'''

# Show Django version
'''python --version
django-admin --version'''