# =====================================================
# CREATING MODELS
# =====================================================

# Models define the structure of database tables.

# Each Model = One Database Table
# Each Object = One Row (Record)
# Each Attribute = One Column

# Models are created inside:
# student/models.py

# After creating or modifying models:
#
# Step 1:
# python manage.py makemigrations
#
# Step 2:
# python manage.py migrate


# =====================================================
# DJANGO MIGRATIONS
# =====================================================

# Migrations are used to synchronize Django models
# with the database.

# Whenever you create or modify a model,
# Django generates migration files.

# Migration Flow
#
# models.py
#      │
#      ▼
# python manage.py makemigrations
#      │
#      ▼
# Migration File Created
#      │
#      ▼
# python manage.py migrate
#      │
#      ▼
# Database Updated
# =====================================================

## CREATE MIGRATION FILE
# Detect model changes
# python manage.py makemigrations

## APPLY MIGRATION
# python manage.py migrate

## SHOW ALL MIGRATIONS
# python manage.py showmigrations

## VIEW SQL GENERATED BY MIGRATION
# python manage.py sqlmigrate student 0001

## CREATE EMPTY MIGRATION
# python manage.py makemigrations --empty student