# Generated by Django 6.0.6 on 2026-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("age", models.IntegerField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
                ("active", models.BooleanField(default=True)),
                ("joining_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("photo", models.ImageField(upload_to="photos/")),
                ("resume", models.FileField(upload_to="resume/")),
            ],
        ),
    ]
